# ===============================
# SERVER CONFIGS
# ===============================

server:
  error:
    include-message: never
    include-binding-errors: never
  port: 2031


  # ===============================
  # SPRING CONFIGS
  # ===============================


spring:
  task:
    scheduling:
      pool:
        size: 10
  main:
    allow-circular-references: true
  application:
    name: Student Management Suite API
  liquibase:
    enabled: true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl:
          auto: none
        show_sql: false
    open-in-view: false
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
  datasource:
    tomcat:
      test-while-idle: true
    url: jdbc:postgresql://localhost:5432/student_suite_db
    username: postgres
    password: password123
  docker:
    compose:
      enabled: false
      file: docker-compose.yml
  mail:
    host: us2.smtp.mailhostbox.com
    port: 587
    username: tests@dreamhub.tech
    password: EOMUApD(A1
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000


    # ==========================================
    # SPRING DOC
    # ==========================================

springdoc:
  show-actuator: true

  # ==========================================
  # APPLICATION LOGGING
  # ==========================================
logbook:
  format.style: http
  filter.enabled: false

  # ==========================================
  # APPLICATION LOGGING
  # ==========================================

logging:
  level:
    root: INFO
    org.zalando.logbook: TRACE
  #    org.springframework.security: DEBUG
  #    org.springframework.web: INFO
  #    org.springframework.web.HttpLogging: DEBUG

  # ===============================
  # = INFO CONFIGS
  # ===============================

info:
  media:
    dir: media
  app:
    name: Fazh Backend APIs
    description: Student Management Suite APIs
    version: 1.0
    basePackage: zw.co.dreamhub
  contact:
    name: US us
    url: https://fazhschool.co.zw
    email: hello@example.co.zw
  url:
    unSecured: /api/v1/public
    secured: /api/v1
  security:
    password:
      salt: zw.co.dreamhub
      saltChars: ABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890
    jwt:
      # base64 encoded https://www.base64encode.org/
      secret: encuY28uZHJlYW1odWIucGFya3dheS4yMDIzLnJpZGUucG9vbGluZy5ib29raW5nLnJlYWx0aW1lLmZhc3Quc2VjdXJlLmNvbnZpbmllbnQuYWxsLmluLm9uZS5yZWxpYWJsZQ==
      jwtExpirationMs: 64800000
      jwtRefreshExpirationMs: 2592000000


  # ===============================
  # = ADMIN
  # ===============================
admin-details:
  username: hello@marlvinzw.me
  password: marlvin123
  phoneNumber: 263781939619